# Generated by Django 3.2 on 2021-05-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe_admin', '0003_auto_20210503_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digitalteam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='digitalteam',
            name='job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(blank=True, help_text='Day of the event', null=True, verbose_name='Day of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Final time', null=True, verbose_name='Final time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Starting time', null=True, verbose_name='Starting time'),
        ),
    ]
